language: python
dist: trusty

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
    - python: 3.8
      dist: xenial
    - python: nightly
    - python: pypy3
  allow_failures:
    - python: nightly

script: python setup.py test
